name: build
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          BUILD_FAIL_ON: warning
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://github.com/w3ctag/meetings/blob/gh-pages/2025/03-Paris/minutes.md#explainer-explainer-adoption-into-wgs-1
          W3C_BUILD_OVERRIDE: |
            status: NOTE
            metadata order: *, !*
